//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpfNetworkDevices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public int id { get; set; }
        public Nullable<int> ip { get; set; }
        public Nullable<int> mask { get; set; }
        public Nullable<int> Gateway { get; set; }
        public Nullable<int> DNS { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
